### ISSUE TITLE
Add support for array metadata block

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-html-pipeline#147]
**Is your feature request related to a problem? Please describe.**
currently it is not possible to specify multiple values for the same metadata, for example to create several `<meta ... >` tags.
for the `Tags`, this is hard coded, by splitting the value by `,`.

### suggestion A: use list

```
+--------------------------------------+
| Metadata                             |
+------------------+-------------------+
| Author           | - John Doe        |
|                  | - Jane Doe        |
+------------------+-------------------+
```

- advantage: intuitive
- disadvantage: breaking, because the list is currently converted to a coma separated value

### suggestion B: duplicate row

```
+--------------------------------------+
| Metadata                             |
+------------------+-------------------+
| Author           | John Doe          |
+------------------+-------------------+
| Author           | Jane Doe          |
+------------------+-------------------+
```

- advantage: not breaking (expect where people have wrong metadata), works probably better for images
- disadvantage: less intuitive

## Furter notes

Metadata from the metadata.json should probably not be merged with the page local metadata, if the value exists in both,
but the page metadata should win.

**Comment by tripodsan** [comment]
they want to have several `<meta property="author" content="..." >` tags in the document.

**Comment by dominique-pfister** [comment]
Thanks, @tripodsan 

Yes, @rofe , they have documents with multiple authors. Right now, they use the indexer's `match` to split the comma-separated list into an array, but this approach would be more intuitive.

/cc: @sdmcraft

**Comment by tripodsan** [comment]
@davidnuescheler what is your take on this?

**Comment by rofe** [comment]
I think until this problem has come up a couple more times in projects, I don't see a downside to simply leaving the comma-separated string in the index and do the splitting on the client/project side.

**Comment by tripodsan** [comment]
> I think until this problem has come up a couple more times in projects, I don't see a downside to simply leaving the comma-separated string in the index and do the splitting on the client/project side.

I thought this is a problem for SEO ?

**Comment by davidnuescheler** [comment]
i agree with @rofe... @tripodsan there is definitely no SEO impact, google uses the DOM not HTML markup.

**Comment by rofe** [comment]
`article:tag` as per [OpenGraph](https://ogp.me/)'s definition is an array of strings, and we wanted to make it easy for blog authors to just provide a comma-separated list of `tags` in the metadata block. 

By contrast, `author` is a custom metadata property. If we want to treat author the same as tags, we would have to turn `author` into an array of standard `article:author` tags, but unfortunately, that would be a breaking change now.

**Comment by tripodsan** [comment]
> we would have to turn `author` into an array of standard `article:author` tags

but this is the idea, afaiu.  the project wants to have multiple `article:author` elements. it can do it client side, but it is clumsy.

> but unfortunately, that would be a breaking change now.

by using suggestion `B`, I don't think this is very breaking. the chance that a document has a duplicate row by mistake is very low.

**Comment by rofe** [comment]
> but this is the idea, afaiu. the project wants to have multiple article:author elements

Ah, then I misunderstood your [earlier comment](https://github.com/adobe/helix-html-pipeline/issues/147#issuecomment-1261427566).

> by using suggestion `B`, I don't think this is very breaking. the chance that a document has a duplicate row by mistake is very low.

Yes, but the current pipeline renders an `author` key in the metadata block as
```html
<meta name="author" content="..." >
```
and your proposal would be to change that to 
```html
<meta property="article:author" content="..." >
```
if I understood your comment above correctly.

Or is your suggestion more generic and not tied to the `author` case specifically?

If there is flexibility in the project to use `article:author` as the key in the metadata block instead of just `author`, then we wouldn't have to "magically" transform the meta name to a property, and collisions with existing content could be avoided.

**Comment by tripodsan** [comment]
no, there is no `article:author` property in the current rendering. I never said that it should be that.

the only change, as provided in the PR #148 from @dominique-pfister is, that if the metadata block has multiple rows with the same key, the respective meta property element gets added multiple time.

so:

```
+--------------------------------------+
| Metadata                             |
+------------------+-------------------+
| Author           | John Doe          |
+------------------+-------------------+
| Author           | Jane Doe          |
+------------------+-------------------+
```

becomes:

```html
<meta name="author" content="John Doe">
<meta name="author" content="Jane Doe">
```

currently the last one wins, and only this shows up:

```html
<meta name="author" content="Jane Doe">
```

**Comment by rofe** [comment]
Ok. There was some confusion around the desired tag output in the above discussion, and I only brought up `article:author` and equivalent to `article:tag` which, as you pointed out above, we do have special handling for. Anyway I think I understand what you mean now :)

Obviously this use case can't be achieved on the client side, and the pipeline change in #148 seems benign. But I'm not sure if this justifies an execption to the projects-first rule for product features...

@davidnuescheler wdyt?

**Comment by sdmcraft** [comment]
This issue came in context of a requirement in Alexander Forbes blogs where a blog article could have several authors. Linking to the issue https://github.com/alexander-forbes/aem-blogs/issues/9 . Alexander Forbes blogs is modelled around Adobe blogs so I am wondering if a similar requirement may come there if there are multiple authors of an article.  Right now its tackled by specifying a delimiter in the author names and then spitting it up by the delimiter while indexing and also on the client side. The problem is that this would not work if the delimiter is legitimately present in a metadata value. For e.g. a `,` in author name. 

I am wondering that rather than attaching a special treatment to a metadata key like  `article:author` , would it still be helpful to have the ability to specify multi-values for metadata attributes ? Right now there does not seem to be a way to do so.

**Comment by tripodsan** [comment]
> would it still be helpful to have the ability to specify multi-values for metadata attributes

this is what this issue is about. currently, there is not need to implement this on the product level. we can reconsider it, when we prepare the next breaking change..

**Comment by jckautzmann** [comment]
We have a use case in Milo where we would need to define several authors, and for each author, a name and a URL, to be able to generate Google-compliant JSON-LD schema for an article news:
```
<html>
  <head>
    <title>Title of a News Article</title>
    <script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@type": "NewsArticle",
      "headline": "Title of a News Article",
      "image": [
        "https://example.com/photos/1x1/photo.jpg",
        "https://example.com/photos/4x3/photo.jpg",
        "https://example.com/photos/16x9/photo.jpg"
       ],
      "datePublished": "2015-02-05T08:00:00+08:00",
      "dateModified": "2015-02-05T09:20:00+08:00",
      "author": [{
          "@type": "Person",
          "name": "Jane Doe",
          "url": "http://example.com/profile/janedoe123"
        },{
          "@type": "Person",
          "name": "John Doe",
          "url": "http://example.com/profile/johndoe123"
      }]
    }
    </script>
  </head>
  <body>
  </body>
</html>
```
as defined at https://developers.google.com/search/docs/appearance/structured-data/article.

More details in (internal ticket) MWPW-114236.

**Comment by mhaack** [comment]
Netcentric project is a new use case where we see this, they have blog posts with 2 authors, like https://www.netcentric.biz/insights/2022/06/optimizing-workflows-workfront.html.

My current approach for mapping in the importer is to:

```
+-------------------------------+
| Metadata                      |
+-----------+-------------------+
| Author    | Author 1, Author2 |
+-----------+-------------------+
```
