### ISSUE TITLE
check if redirects also send custom headers

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-html-pipeline#153]
**Description**
from slack:

> I think it works fine if it wasn't 301. let me check..

> Unfortunately the pipeline will not return your response headers with the 301 as it stands today.

**Comment by seanchoi-dev** [comment]
Here is slack thread: https://adobe-mwp.slack.com/archives/C9KD0TT6G/p1664925181924599
Here are some of many broken pages: 

- https://business.adobe.com/jp/blog/the-latest/dx-adobe-analytics-consumers-spent-1-billion-less-on-domestic-flights-in-april-and-prices-continue-to-rise

- https://business.adobe.com/jp/blog/the-latest/dx-how-data-and-digital-transformation-is-helping-cmos-jp
