### ISSUE TITLE
allow any custom header via headers.json

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-html-pipeline#199]
currently only a small set of headers are supported in the headers.json, this is a left over from where the headers were storeed in the metadata.json.

suggestion:
- allow any header to be added via the headers.json

**Comment by tripodsan** [comment]
@davidnuescheler WDYT?

**Comment by rofe** [comment]
Paraphrasing @davidnuescheler from Slack: 
> then i guess we'll have to open that up

**Comment by rofe** [comment]
This is already implememted in v7.
