### ISSUE TITLE
redirects on existing json resources don't seem to work

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-html-pipeline#223]
**Description**
- create a tabular resource and preview it, eg `/foo.json`
- add a redirect for that resource `/foo.json` -> `https://www.adobe.com`
- preview the redirects sheet

observe: the  json is rendered instead of the redirect response.

**Comment by vhargrave** [comment]
As discussed on slack, this is a bug that we'd like to have fixed for Adobe Express as well. 
https://adobe-mwp.slack.com/archives/C9KD0TT6G/p1681398155073459
@tripodsan @rofe @trieloff

**Comment by trieloff** [comment]
I think the issue mentioned on Slack applied to HTML, not JSON.

**Comment by vhargrave** [comment]
It did - Maybe the issues have something to do with each other, but I've gone ahead and created and created a separate bug now just in case 👍 - https://github.com/adobe/helix-html-pipeline/issues/296
