### ISSUE TITLE
add possibility to authenticate preview only

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-html-pipeline#274]
eg:

- `access.allow.live=*`
- or `access.allow.live=anonymous`

this would also allow for different creds:

```
access.allow.preview=authors.json
access.allow.live=viewers.json
```

better to reverse structure:

### example of preview only auth:

```
access.preview.allow=authors.json
```

### example of different access groups for preview and live; including api key for live

```
access.preview.allow=authors.json
access.live.allow=viewers.json
access.live.apiKeyId=xyz
```

### only allow access via api key and authors

```
access.apiKeyId=xyz
access.live.allow=helix@adobe.com  // required for api key access
access.preview.allow=authors.json
access.preview.allow=helix@adobe.com // users don't inherit from access.allow
```

## workaround

Pre-authenticate requests to .live via an `API_KEY` on the production CDN

**Comment by amol-anand** [comment]
I have a customer asking for authentication only for preview and not for live.

**Comment by auniverseaway** [comment]
+1 to this request. This would be great for us on adobe.com

**Comment by davidnuescheler** [comment]
@tripodsan i think this is probably not a pipeline only issue or is it? if this has no impact on the delivery stack upstream that would be great.

**Comment by tripodsan** [comment]
> @tripodsan i think this is probably not a pipeline only issue or is it? if this has no impact on the delivery stack upstream that would be great.

@davidnuescheler both. ultimately, the .live requests need to be able to fetch the content unauthenticated. for that several things must happen:
- the edge dicts on .live that mark authenticated sites needs to be removed (admin issue)
- when .live fetches content via .page if needs to be able to do this unauthed. this can be done by not enforcing auth on the `live` partition. this is a html-pipeline issue

**Comment by davidnuescheler** [comment]
that's great thanks @tripodsan for the details.
