### ISSUE TITLE
allow restriction of content access via owner/repo configuration

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-html-pipeline#277]
It should be possible to limit content rendering to a set of _trusted_ repositories via the `/.helix/config.json` (`config-all`).

possible configuration names:

<img width="496" alt="image" src="https://user-images.githubusercontent.com/917628/225939500-1c1b3d41-85a6-4380-94cf-13c29bb1c6f3.png">

my favourite is: `trust.repository`

**Comment by davidnuescheler** [comment]
yeah, sounds great. the only thing that i think is a bit unexpected with the term "trust" is that nobody would say that they "trust" every repository by default... i think "allowing" all repository by default seems more understandable.

**Comment by trieloff** [comment]
I'd say you demand or require the repository

**Comment by tripodsan** [comment]
> I'd say you demand or require the repository

so maybe:

| key | value |
|-----|------|
| `require.repository` | `adobe/*` |

or maybe merge it into `access` ?

| key | value |
|-----|------|
| `access.require.repository` | `adobe/*` |
| `access.allow` | `*@adobe.com*` |
| `access.allow` | `*@pfizer.com*` |
