### ISSUE TITLE
Support alternative html origins able to implement fill spectrum tag authoring.

### ISSUE THREAD

**Issue by ieb** [adobe/helix-html-pipeline#288]
The markup that is produced by hlx.page is clean and minimalist but it lacks much of richness of modern html. I believe this is by design since customisation of the html is performed client side by javascript, however this requires that javascript code is written to perform that customisation after the dom is received into the browser, which in turn potentially delays the time to first interactive and other key metrics.

I also realise that there is absolutely no desire in this project to support the richness of modern html being delivered as that would require endless per project customisation, and so I am wondering if it would be possible to support configuring a Franklin GitHub Project to use and alternative origin as a source for the authored content delivered from. The behaviour of that origin would need to conform to a strict technical contract, but adding support for this might allow sites that need markup not supported (eg `<dl>, <article>, <template>` etc etc, following patterns often used at  https://web.dev), or an authoring system other than Word or GDocs where it seems impossible to generate this markup, and opportunity to use Franklin as their Content composition platform.

The pattern would be:

- in the projects github an end point is configured eg `https://authoring.example.com/ready/` 
- When reload is triggered via the Franklin Admin API, the content would be fetched by appending the path to that url eg reload for `https://<branch-<repo>-<owner>.hlx.page/product/catalog`   fetches `https://authoring.example.com/ready/product/catalog` 
- output is saved for delivery.

This might not be the right place to make this suggestion as it may not be implemented here, but it does seem like a good place to have the discussion.

**Comment by ieb** [comment]
Not sure if enhancement is the right label, but I cant change it to discussion.

**Comment by tripodsan** [comment]
so you basically want to build a static webserver? i.e. upload the HTML via some external word->html mechanism to a storage and deliver it as is via the pipeline? if so, then maybe a static webserver would be the better choice :-)
