### ISSUE TITLE
Tables with rowspan are not correctly represented in HTML

### ISSUE THREAD

**Issue by synox** [adobe/helix-html-pipeline#290]
**Description**
When a table has rowspan, the cells on the next rows, that are part of the rowspan, are omitted. This way the cells in the 2nd row and 2nd column are not correctly positioned. 

Word: 
<img width="662" alt="Screenshot 2023-04-04 at 14 37 30" src="https://user-images.githubusercontent.com/2250964/229928472-9cda7dab-8e5f-439f-8da3-c8df3e08ccd7.png">

MD: 
```markdown
+------------------+
| Table            |
+-------+----------+
| First | Second 1 |
|       +----------+
|       | Second 2 |
+-------+----------+
```

HTML
```html
<div>
  <div class="table">
    <div>
      <div>First</div>
      <div>Second 1</div>
    </div>
    <div>
      <div>Second 2</div>
    </div>
  </div>
</div>

```

**To Reproduce**
1. See https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/Shared%20Documents/sites/VolvoGroup/vg-volvotrucks-us/drafts/wingeier/Document1.docx?d=w929d92f91b38471b999ca74b5b67a913&csf=1&web=1&e=Ot2f5L

**Expected behavior**
Every cell should be repeated in the the second row, even the invisible ones. 

**Additional context**
Some components on https://main--vg-volvotrucks-us--hlxsites.hlx.page/drafts/documentation/block-inventory have rowspan.

### Workaround

Don't merge cells vertically in Word. I am worried that the authors might eventually do this and run into this bug.

**Comment by tripodsan** [comment]
please note that toplevel tables are always converted to blocks. if yo want a _real_ table, put it inside a cell of a block.

**Comment by synox** [comment]
@tripodsan `Table` is just a placeholder for another block name, we don't actually want a table here. Please reopen. 
Table in table does not fit here.
