### ISSUE TITLE
Image replacement title property is not output by the pipeline

### ISSUE THREAD

**Issue by tmaret** [adobe/helix-html-pipeline#308]
**Description**

Alternative title is not output by the pipeline although it is set properly on an image located inside a word document. 

Alternative description is output properly as `alt` attribute on the `img` tag.

**To Reproduce**

1. Create a word document in Sharepoint
2. Add an image in the document
3. Set the alternative title to "I went through the pipeline"
4. Preview the document
5. Render the document as .md and find the title "I went through the pipeline" in the output
6. Render the document as HTML and see that the title is not in the output

If you can access it, you may also use [this word document](https://adobe.sharepoint.com/:w:/s/HelixProjects/ETNu8FsJu0ZHi_Ue9w89JzAB56Q-do2YrfSnFbiFvUqaUA?e=012ZN1)

**Expected behavior**

I expect the replacement title value set on an image within a word document to be output as `title` attribute on the `img` tag.

**Screenshots**

The following screenshot shows the alternative title and descriptions set on an image in within a word document

<img width="1904" alt="alternative" src="https://user-images.githubusercontent.com/1628648/236547119-bf620c5d-e5ff-41b7-b1ee-72ea43ae902e.png">

The following screenshot shows the Markdown output of the document that contains the image. The alternative title is present in the output, as expected.

<img width="1904" alt="md-fine" src="https://user-images.githubusercontent.com/1628648/236548478-e71d9416-9ecb-443d-973b-c5dd7d92ae62.png">

The following screenshot shows that the alternative title is not contained in the HTML output.

<img width="1811" alt="Screenshot 2023-05-05 at 21 12 37" src="https://user-images.githubusercontent.com/1628648/236550258-93003f75-ab41-4b02-b60a-c96a0f322e16.png">

**Version:**
14.21.2

**Additional context**

https://cq-dev.slack.com/archives/C04RN3CQWBZ/p1683295645721079?thread_ts=1683295547.817699&cid=C04RN3CQWBZ

**Comment by tmaret** [comment]
Opened a PR with the fix and test https://github.com/adobe/helix-html-pipeline/pull/312

**Comment by tripodsan** [comment]
@tmaret what is the use case ?

**Comment by tmaret** [comment]
@tripodsan zeiss.[com|de] sets `alt` and `title` attributes on `img` tags. We are porting the news section to Franklin and thus would like to have support for both. Use case is also to close the loop, indeed the Franklin importer supports both attributes but the `helix-html-pipeline` only supports `alt` atm.
