### ISSUE TITLE
add custom attribute support for metadata

### ISSUE THREAD

**Issue by dkuntze** [adobe/helix-html-pipeline#336]
**Is your feature request related to a problem? Please describe.**
Some external integrations (search appliances, etc) require that the head meta tags have custom attributes like `class` or `data-type`. Most the integrations don't support js, so a simple block won't suffice here - it has to be in the returned HTML.
example:
https://swiftype.com/documentation/site-search/crawler-troubleshooting#javascript
https://www.vonage.com/unified-communications/features/admin-portal/ (view source)

**Describe the solution you'd like**
I think it could be as simple as the parens method that blocks use:
metaname (class=something, data-type=anotherthing) | metavalue

**Describe alternatives you've considered**
Not sure there is an alternative

**Additional context**
values that I'm trying to replicate:
`
<meta class="swiftype" name="product" data-type="enum" content="product/unified-communications/feature" />
<meta class="swiftype" name="ff_product" data-type="enum" content="product/unified-communications" />
<meta class="swiftype" name="ff_product" data-type="enum" content="product/unified-communications/feature" />
<meta class="swiftype" name="content_section" data-type="enum" content="products" />
<meta class="swiftype" name="topic" data-type="enum" content="topic/flexibility" />
`

**Comment by davidnuescheler** [comment]
This seems very unusual and also undesirable from a search engine standpoint… looks like tech debt to me. 

It would be great to know the specific integration and tooling that’s relying on this non-standard / non spec compliant use of meta tags.

If this is a hard requirement on the markup I would recommend a cloudflare worker, but generally would recommend to the customer to use a more flexible search provider, if the search is even needed.

**Comment by dkuntze** [comment]
@davidnuescheler Here's the search engine in question's doc page for meta:

https://swiftype.com/documentation/site-search/crawler-configuration/meta-tags

**Comment by tripodsan** [comment]
won't fix.
