### ISSUE TITLE
skip rewrite-icons for certain conditions

### ISSUE THREAD

**Issue by maxakuru** [adobe/helix-html-pipeline#348]
The current behavior for icons is to rewrite any text that matches [`/:(#?[a-z_-]+[a-z\d]*):/gi`](https://github.com/adobe/helix-html-pipeline/blob/main/src/steps/rewrite-icons.js#L16) with a span

**Problem:** this replaces strings that intentionally use colons inside them, like URNs

There are a couple cases I think this could be avoided without being too much of an impact:
1. inside `code` elements
- I would argue it's unlikely authors intend to insert icons inside code blocks, at least when being used for code
- this would match github/slack functionality, eg. :+1: `:+1:`
2. inside urns/hrefs
- URNs may exist in content
- some links contain URNs or path segments that resemble URNs, eg. sharepoint
- unlikely icons are intentionally inserted into those patterns
  - `(?<!(?:https?|urn)[^\s]*):(#?[a-z_-]+[a-z\d]*):`
  - can't begin with `urn:`, `http:` or `https:`

**Comment by maxakuru** [comment]
this would technically be a breaking change, but not sure how often each case might be relied on right now

wdyt @tripodsan @trieloff @dominique-pfister ?

**Comment by tripodsan** [comment]
I think this is ok. @davidnuescheler should decide :-)

**Comment by bstopp** [comment]
What about not processing unless they are terminated by spaces?

```
/\s:(#?[a-z_-]+[a-z\d]*):\s/gi
```

**Comment by maxakuru** [comment]
@bstopp I think that is contrary to what people are used to in places like slack or:rocket:github, which is nice to stick close to for icons imo

for URNs I think case 2 could just be adjusted to include `urn:` as an ignored scheme along with `https?:`
