### ISSUE TITLE
Email ids with a '_' in them are not parsed correctly

### ISSUE THREAD

**Issue by sharmrj** [adobe/helix-html-pipeline#358]
**Description**
When there are underscores in an email address, they are incorrectly parsed. Example: `abc_xyz@email.provider` gets turned into `"abc_"<a href="mailto:xyz@email.provider">xyz@email.provider </a>`. You can find an actual example [here](https://stage--helpx-internal--adobecom.hlx.page/content/help/en/internal/individual/policy-process/value-incentive-plan-complete-plan-pro-video-edition-for-creati#license-account-setup)
Since ‘_’ is [a valid character](https://datatracker.ietf.org/doc/html/rfc5322#section-3.2.3) in the local part of an email address, this is unexpected behavior.

**To Reproduce**
You can either go to https://stage--helpx-internal--adobecom.hlx.page/content/help/en/internal/individual/policy-process/value-incentive-plan-complete-plan-pro-video-edition-for-creati#license-account-setup
Or you can try inserting an email address with an underscore in the local part in a fresh word document and previewing it.

**Expected behavior**
The email address gets correctly parsed so long as the email is valid.
For instance, `abc_xyz@email.provider` should get turned into `<a href="mailto:xyz@email.provider">abc_xyz@email.provider </a>`

**Screenshots**

<img width="289" alt="Screenshot 2023-07-21 at 1 03 55 PM" src="https://github.com/adobe/helix-html-pipeline/assets/118168183/cb064f09-1e94-472d-b106-c400b2fd8d7a">

**Version:**
14.21.4

**Additional context**
https://datatracker.ietf.org/doc/html/rfc5322#section-3.2.3

**Comment by tripodsan** [comment]
I just realized that the email link is already wrong in the docx:

<img width="518" alt="image" src="https://github.com/adobe/helix-html-pipeline/assets/917628/70ac47a2-b236-4986-b712-a43c0abf1858">

and in the markdown:

<img width="526" alt="image" src="https://github.com/adobe/helix-html-pipeline/assets/917628/19a1983b-d8c5-496b-9789-660dbd9ee912">
