### ISSUE TITLE
fallbacks in metadata

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-html-pipeline#382]
if metadata is set explicitly to an empty string in a doc we should not fallback to default, but keep things empty.

i think there is an implementation of that for the spreadsheet approach here. 
https://github.com/adobe/helix-html-pipeline/issues/214

also, inheritance for `twitter:` should go through `og:` and not directly to the default. it is much more common to have diverging metatdata between SEO (non prefixed) and social than between `twitter:` and `og:` prefixes.

**Comment by tripodsan** [comment]
suggested changes:

- empty cells in local metadata (`title`, `description`, `image`, `canonical`, `image`, `image-alt`) cause the respective metadata value to be empty. previously, it would fallback to the metadata heuristically extracted from the content (first H1, first paragraph, hero image).
- `twitter:title`, `twitter:description`, `twitter:image` have a fallback on their `og:*` counterparts and not on the default metadata heuristically extracted from the content (first H1, first paragraph, hero image).
- double double-quote values (`""`) in the metadata-sheets (not documents) will suppress rendering of the metadata element.
