### ISSUE TITLE
Header overflow on authenticated sites when page url is long

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-html-pipeline#418]
- Open https://main--inside-aem--adobe.hlx.live/en/publish/2023/09/29/aem-pla-blog-building-infrastructure-part-vip-pushing-culturetecture-limits
- Authenticate

You get a `Header overflow` error page.

Workaround: 
- https://main--inside-aem--adobe.hlx.live (or any shorter url on that site)
- Authenticate
- Navigate to  https://main--inside-aem--adobe.hlx.live/en/publish/2023/09/29/aem-pla-blog-building-infrastructure-part-vip-pushing-culturetecture-limits

cc @tripodsan

**Comment by tripodsan** [comment]
this is fixed.
