### ISSUE TITLE
static html from the code bus with selectors no longer works

### ISSUE THREAD

**Issue by shsteimer** [adobe/helix-html-pipeline#481]
**Description**
Due to recent changes https://github.com/adobe/helix-html-pipeline/pull/471 static html served via the cod bus that contains a selector fails to load with a 404

**To Reproduce**
1. add a static html file to code bus with a selector, something like `/blocks/my-block/my-block.selector.html`
2. attempt to access that file
3. see 404 response with `invalid path` error

**Expected behavior**
static html should be served as expected

**Version:**
run: `$ hlx --version`

**Additional context**
See thread with customer at https://adobe-dx-support.slack.com/archives/C03GXBSC72T/p1704214470859999

they are fixing on their side to work around regression, so unsure if we must fix this or not. But I do think we should at least try to make sure the cli behaves the same to avoid customer confusion

**Comment by shsteimer** [comment]
Looking into this a bit more, I think what happened is that these requests never used to make it to this service? Now that they do, they are failing the path info checks.

I think the path info check could be simplified to just:
```
 // only support selectors with html
  if (info.selector) {
    return info.extension === '.html';
  }
```

but that would require changing a few other tests to match that expectation.

@tripodsan curious for your thoughts.

**Comment by tripodsan** [comment]
fixed
