### ISSUE TITLE
New folder mappings are not reflected on existing branches other than main

### ISSUE THREAD

**Issue by cpilsworth** [adobe/helix-html-pipeline#561]
**Description**
When a new folder mapping is added to `fstab.yml`, the mapping is not reflected on any existing branches other than `main`.  Any new branches created after the `fstab.yml` change is committed will reflect the change.  

**To Reproduce**
1. Create a new branch from `main` named `pre-folder`
2. Add a new folder mapping to `fstab.yml`
3. Create a new branch named `post-folder`

The new folder mapping is only available on URLs with the `main` and `post-folder` branches.  Any requests to the folder on `pre-folder` will have a 404 returned.

**Expected behavior**
The folder mapping should be available on urls with the `main`, `pre-folder` and `post-folder` branch refs.

**Screenshots**

**Version:**
run: `$ hlx --version`
> `16.2.8`

**Additional context**
The behaviour is not mentioned on https://www.aem.live/developer/folder-mapping.  It's easy to think that the folder mapping has not worked in the context of your current working branch.

**Comment by tripodsan** [comment]
I'm not sure that this is expected, as you might want to try a new foldermapping in a developer branch. especially since the code dealing with the mapped document is branch local.

**Comment by cpilsworth** [comment]
Any new code to deal with a mapped document would need to be added to a _new_ branch created _after_ the `fstab.yml` is committed.  

Without knowing better... my personal expectation here was that I could:
1. create `feature` branch
2. add the folder mapping
3. add the code to utilise the folder mapping
4. test successfully
5. merge `feature` branch with `main` via PR

instead it was more like:
1. create `feature` branch
2. commit the folder mapping
3. commit the code to utilise the folder mapping
4. test without success
6. notice that other members of the team had created another branch from their own feature branches
7. create a `feature2` branch from feature
8. test successfully with feature2 ref
9. merge `feature2` branch with `main` via PR
10. delete redundant `feature` branch

I guess if you plan ahead and commit your folder mapping before creating your feature branch, then it works ok.  However there's nothing in the docs to prepare you for that.

**Comment by hannessolo** [comment]
> as you might want to try a new foldermapping in a developer branch

As far as I can tell, only the `fstab.yaml` on the default branch is respected. So you can't test foldermapping on a branch.

To me it would be most intuitive to have each branch respect the foldermapping of that branch's `fstab.yaml`, but while that's not the case, the solution @cpilsworth suggests makes sense, to have all branches respect main, regardless of when they were created.

**Comment by tripodsan** [comment]
> to have all branches respect main, regardless of when they were created.

yes. unfortunately this is currently not possible, as the config internally also holds the contents of the head.html, which is per-branch. so we can't just load the `main` config.

in helix5, you will be able to just create a new `site` for testing the changes of a new folder mapping. but for the current helix version, the only workaround is to explicitly code-sync the fstab of the branch, in order to update the folder mapping information from the main branch.
