### ISSUE TITLE
Metadata Image URLs not rewritten

### ISSUE THREAD

**Issue by bstopp** [adobe/helix-html-pipeline#604]
Some metadata image URLs are not being rewritten to the production host domain.

Examples:  
* https://www.merative.com/
* https://www.famous-smoke.com/cigaradvisor

I believe that the URLs are not-rewritten if you set the image  value explicitly in the metadata block.

**Comment by tripodsan** [comment]
I cannot reproduce it in tests, see:
https://github.com/adobe/helix-html-pipeline/blob/d0c173f21942f6fb123ff6d4288364d4b9f0ec98/test/fixtures/content/image-from-meta-rewrite.html#L7

**Comment by tripodsan** [comment]
@bstopp the image in the metadata of merative is a link and not an image:

```
<https://main--merative2--hlxsites.hlx.page/images/meta/default-meta-image.png>
```

**Comment by bstopp** [comment]
> the image in the metadata of merative is a link and not an image:

Yes, as is the one from Famous Smoke - because they wanted to use a shared image reference for all pages. But even as a link, it should be re-written to the `live` or production domain, as any other link.
