### ISSUE TITLE
subtle difference between `.plain.html` and extensionless of self-referential links

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-html-pipeline#642]
https://main--aem-boilerplate--adobe.aem.page/footer produces

```
 <a href="#consent">Cookie preferences</a>
```

and https://main--aem-boilerplate--adobe.aem.page/footer.plain.html

```
<a href="/footer#consent">Cookie preferences</a>
```

i think the extensionless rendition is more desirable, particularly in fragments.

if we would change this, it is technically breaking and it could be interesting to scan content for self-referential resources that access `.plain.html` just to be gauge potential impact.

**Comment by tripodsan** [comment]
> if we would change this, it is technically breaking and it could be interesting to scan content for self-referential resources that access `.plain.html` just to be gauge potential impact.

how would you do this?

**Comment by davidnuescheler** [comment]
@tripodsan thanks for the scan. it seems pretty rare to get self-referential that are used as fragments. i will proactively approach projects that have are highly likely to have to used self-referential links in "fragment" use-cases.
