### ISSUE TITLE
[metadata] server-sided json-ld schema support

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-html-pipeline#648]
we currently add schema data via json-ld on the client side, which works well in most cases. this usually looks something like this...

```
.
.
.
<head>
.
.
.
<script type="application/ld+json">
{ ... }
</script>
</head>
```
in cases where there are frequent changes it can be advantageous for SEO to have the schema rendered right into the server.

i trivial initial implementation could just consider a `json-ld` field in metadata which contains the json-ld value. there are a couple of limitations with that.

(1) authoring comfort: editing a JSON string in a spreadsheet or the metadata table in a doc may be very cumbersome, however it is unlikely in most situations that items would be authored that way.
(2) per field size limitations: JSON-LD can get relatively sizeable and it doesn't seem inconceivable that it goes beyond the 32k limit in excel
(3) inflated size of metadata.json: adding a lot of schema data may inflated the decompressed in memory size quite dramatically, i am not sure how much this would affect the gzip'd JSON, as the content is highly redundant and can probably be compressed easily.

i think the best way forward on this may be build this in feature flagged (or undocumented) and see if it holds up in real-life or if we need to consider a different approach to store (or collect) the json-ld mid-term.

**Comment by tripodsan** [comment]
I fear that the metadata.json gets more and more used like a database and away from the tree-like tagging of pages.
especially the "spreadsheet base editing" and I'd assume also this new json-ld approach will lead the massive metadata aggregates that are included in the config-service response.

I wonder if it would make sense to collect all non-regexp metadata information in a separate (content stored) `metadata-aggregate.json` that is loaded additionally by the pipeline.

in helix4, the metadata is aggregated during preview/publish and stored in configall.json
in helix5, the metadata is aggregated dynamically in the config service.

maybe we should keep the helix4 mechanics also for helix5 and aggregate the metadata.json during preview/publish and then include it in the config-service resonse if "small", but mark it as swapped-out, when large.

**Comment by davidnuescheler** [comment]
i am thinking that we are indeed getting to a place where it these spdreasheets (or jsons) are practical for management or ingestion, but become a bigger and bigger drain on delivery... i wonder if it would make sense to have an extension of the metadata facility that operates with a similar rollout as the redirects.

i could see something like a <path>.metadata.json that sits next to the `.md` and contains all the metadata information and the overall `metadata-aggregate.json` just says that it exists. this would also solve the umbrella last modified change which has downstream SEO / crawling budget benefits.

in my mind that conversation is a little bit distinct from the json-ld discussion, and more generally applicable.
i think we have some customers who would be willing to try out the json-ld with a couple of thousand pages with about 20kb-30kb uncompressed data each. which would turn maybe into about ~100mb uncompressed json. what do you think is the largest size of aggregate metadata we handle?

**Comment by davidnuescheler** [comment]
after a second look, i think the numbers are at least one order magnitude smaller... so we would maybe land in a place where we have about 10m in uncompressed json data from json-ld, that is hopefully broken up into multiple spreadsheets.

**Comment by tripodsan** [comment]
> which would turn maybe into about ~100mb uncompressed json. what do you think is the largest size of aggregate metadata we handle?

in helix4, there is no technical limit of the metadata, as it is aggregated in the admin during preview/publish and stored in config-all. the helix4 pipeline reads it from there.

but in helix5, all metadata is included in the config service response, hence obliges the 6mb labmda response limit. our jsons can typically be compressed 10%, so a 60mb raw config is probably supportable.

also, with the new key/value format of the medatata, we waste alot of memory (this is probably not a problem for the compressed size).

**Comment by tripodsan** [comment]
> i could see something like a .metadata.json that sits next to the `.md` and contains all the metadata information and the overall `metadata-aggregate.json` just says that it exists. this would also solve the umbrella last modified change which has downstream SEO / crawling budget benefits.

for non-glob metadata, this would certainly make sense. it would also be benefiial to cache purging, as changes to the metadata would not need to invalidate all content.

**Comment by davidnuescheler** [comment]
@tripodsan i think these are two discussions, the addition of `json-ld` in the pipeline rendering seems trivial and in my mind has no real down side to status quo.

the more scalable metadata implementation is only vaguely related, so i created an issue in https://github.com/adobe/helix-html-pipeline/issues/651 and https://github.com/adobe/helix-admin/issues/2354
