### ISSUE TITLE
Metadata missing required og:type

### ISSUE THREAD

**Issue by hparra** [adobe/helix-html-pipeline#685]
**Description**

OG protocol requires the `og:type`, e.g. `<meta property="og:type" content="video.movie" />` [1]

**Expected behavior**

Any OG tags in meta should include `og:type`.

In [2] consider:

```js
  'og:type': meta['og:type'] || 'website',
```

The indirect default is "website" [3]:

> Any non-marked up webpage should be treated as og:type website

"article" is valid in many cases.

**Related**

AEM may want to consider generalizing a default "type" meta as there is overlap with other metadata like JSON-LD. For example, they both have 'website' and 'article' in common.

Twitter uses OG properties so pipeline duplicating some props by default may be redundant [4] 

**References**

1. https://ogp.me/#metadata
2. https://github.com/adobe/helix-html-pipeline/blob/7959603df0d19b75b7fe2abea662b48c1dc504f8/src/steps/extract-metadata.js#L268
3. https://ogp.me/#no_vertical
4. https://developer.x.com/en/docs/x-for-websites/cards/overview/markup

**Comment by tripodsan** [comment]
@davidnuescheler WDYT?

**Comment by tripodsan** [comment]
this can easily be added by projects using global metadata... don't know if it's worth to break backward compatibility.

**Comment by hparra** [comment]
Not sure what backwards compat you're referring to.

OK probably no big deal since FB uses 'website' if it's not defined. Twitter will render summary if 'twitter:card' is not defined but 'og:type' et al are [2] Unsure about other sites.

1. https://developers.facebook.com/docs/sharing/webmasters/#markup
2. https://developer.x.com/en/docs/x-for-websites/cards/overview/markup

**Comment by tripodsan** [comment]
> Not sure what backwards compat you're referring to.

we're altering the metadata for all customers. so not sure if this doesn't have undesired side effects.

as a work around, I suggest to use the global metadata, and add the `og:type` for `/**`
