### ISSUE TITLE
Folder mapped metadata not applied to physical pages in folder mapped paths

### ISSUE THREAD

**Issue by buuhuu** [adobe/helix-html-pipeline#758]
**Description**
When using folder mapped virtual pages, it is possible to provide a bulk metadata spreadhseet that is applied to the these virtual pages. https://www.aem.live/docs/bulk-metadata#folder-mapped-metadata

When creating a physical page inside the folder mapped path, the metadata spreadsheet is not applied anymore, only the regular and additional bulk metadata spreadsheets are applied.

Form a users point of view, metadata should be applied on a path no matter it virtual page or a physical page in a folder mapped path.

**To Reproduce**
1. setup a site with folder mapping
2. add a folder mapped metadata sheet
3. preview everything and verify the folder mapped metadata is applied to the folder mapped pages
4. create a physical page in the folder mapped path
5. the folder mapped metadata is not applied

**Expected behavior**
The folder mapped metadata is applied.

**Additional context**
https://cq-dev.slack.com/archives/C064DHSP4G2/p1732219349468749

**Comment by mrugesh-adobe** [comment]
We are eagerly awaiting a fix, as the SAP team has planned to go live by December 13th. A resolution at the earliest would be greatly appreciated.

Additionally, here’s a detailed thread outlining the same issue encountered during the SAP project: [Slack Thread Link](https://cq-dev.slack.com/archives/C05QU7MMRNF/p1732542028937429).

Looking forward to your update!

**Comment by sanmishr** [comment]
observed same issue for SAP Design System - https://adobe-acs.slack.com/archives/C05QU7MMRNF/p1733148292719009?thread_ts=1732542028.937429&cid=C05QU7MMRNF
